dataset_path: CohereLabs/kaleidoscope
dataset_name: null
test_split: train
output_type: multiple_choice
doc_to_text: !function utils.kaleidoscope_blind_doc_to_text
doc_to_target: !function utils.kaleidoscope_blind_doc_to_target
doc_to_choice: !function utils.kaleidoscope_blind_doc_to_choice
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
